### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by reisi-h** [VahidN/DNTCaptcha.Core#126] opened 2021-12-18 11:41 UTC
# Summary of the issue
i get error 
  - Unable to find package SixLabors.ImageSharp.Drawing with version (>= 1.0.0-beta13.15)
  - Found 13 version(s) in nuget.org [ Nearest version: 1.0.0-beta13 ]
when i try install latest version from Nuget package manager windows

## Environment

```
DNTCaptcha.Core version: 4.3.1
.NET Core SDK version: .Net Core 3.1
IDE: Visual Studio 2019
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment] 2021-12-18 11:51
It's duplicate of #https://github.com/VahidN/DNTCaptcha.Core/issues/124

**Closed by VahidN** 2021-12-18 11:51 UTC
