### ISSUE TITLE
.netcore app deployed to an EKS cluster running behind a Loadbalanacer on AWS

### ISSUE THREAD

**Issue by alreichf** [VahidN/DNTCaptcha.Core#106] opened 2021-04-22 15:58 UTC
# Summary of the issue

## Environment

```
DNTCaptcha.Core version:  3.5.0
.NET Core SDK version: 3.1
IDE: EKS with docker running behind a ELB
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:
This is when i run locally on my machine
![image](https://user-images.githubusercontent.com/9037080/115746015-e1dbeb80-a38b-11eb-991a-37dfb18ec544.png)

This is when i try accessing via an ELB and containers running on EKS

![image](https://user-images.githubusercontent.com/9037080/115746139-fddf8d00-a38b-11eb-9e3d-9707289940e5.png)

```
Exception message:
Full Stack trace:
```

**Comment by alreichf** [comment] 2021-04-22 16:00
The problem is everything works fine on my local machine(vs 2019)

but when i deploy the code to EKS the POST works but the GET request returns a 500

**Comment by alreichf** [comment] 2021-04-22 16:10
im now wondering if its linked to the DNT options for the services or something related to cors. but the first POST request shouldve failed then :/

**Comment by VahidN** [comment] 2021-04-22 16:50
- Probably it's duplicate of https://github.com/VahidN/DNTCaptcha.Core/issues/101.
- Also you should log the internal server errors (status-code=500) to see what's the real problem.

**Closed** 2021-04-23 06:43 UTC

**Comment by alreichf** [comment] 2021-04-27 12:48
Thank you.. the problem is im using serilog and so im only logging info :/.. still let me check..

but out of curiosity
if my client is British Summer time(UTC+1) and the server is UTC do i need to make any adjustments for the cache please?

like so: 

            services.AddDNTCaptcha(
                o => o.UseCookieStorageProvider()
                     .AbsoluteExpiration(minutes: -1) // set this to a negative number
                     .ShowThousandsSeparators(false)
            );

**Comment by alreichf** [comment] 2021-04-27 14:18
ok.. got this exception now: Its the same as #101 

its not lambda specific but related to linux... on windows it runs perfectly.. my current OS is ubuntu_18.

System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or director

**Comment by alreichf** [comment] 2021-04-27 14:24
Thanks very much @VahidN !
